"use client";

import React from "react";
import { ChevronLeft } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="pt-32 pb-24 min-h-screen px-6 bg-white overflow-hidden relative">
      <div className="max-w-4xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-gray-900 transition-all font-black text-xs uppercase tracking-widest mb-12 group">
          <ChevronLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> Back to Home
        </Link>
        
        <header className="mb-16 space-y-4">
          <h1 className="text-5xl md:text-7xl font-black text-gray-900 tracking-tight">Terms of <span className="text-yellow-600">Service</span></h1>
          <p className="text-gray-400 font-bold uppercase tracking-[0.2em] text-xs">Last Updated: April 14, 2026</p>
        </header>

        <div className="prose prose-xl prose-gray max-w-none space-y-12 text-gray-600 font-medium leading-relaxed">
          <section className="space-y-6">
            <h2 className="text-3xl font-black text-gray-900 tracking-tight border-b-2 border-banana inline-block pb-2">1. Use of Content</h2>
            <p>All prompts, images, and tutorials provided on this platform are for educational and inspirational purposes. By using this site, you agree to respect the intellectual property of our creators.</p>
          </section>

          <section className="space-y-6">
            <h2 className="text-3xl font-black text-gray-900 tracking-tight border-b-2 border-banana inline-block pb-2">2. AI Generation Rights</h2>
            <p>While we provide the prompts, the final output generated by third-party AI tools (like Midjourney, Sora, or Runway) is subject to the terms of those respective platforms. We do not claim ownership of images generated by you using our provided prompts.</p>
          </section>

          <section className="space-y-6">
            <h2 className="text-3xl font-black text-gray-900 tracking-tight border-b-2 border-banana inline-block pb-2">3. Prohibited Conduct</h2>
            <p>Users are prohibited from using our prompts to generate content that is illegal, harmful, or violates the safety guidelines of AI model providers. We reserves the right to terminate access to our community for anyone who violates these standards.</p>
          </section>

          <section className="space-y-6 border-t border-black/5 pt-12 mt-20">
            <p className="text-sm text-gray-400 italic">By continuing to use this platform, you acknowledge that you have read and agreed to these terms.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
